
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace Gadgeteer2Xively
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module definitions
        Gadgeteer.Modules.GHIElectronics.Button button;
        Gadgeteer.Modules.GHIElectronics.Display_TE35 display_TE35;
        Gadgeteer.Modules.GHIElectronics.Ethernet_J11D ethernet_J11D;
        Gadgeteer.Modules.GHIElectronics.LightSensor lightSensor;
        Gadgeteer.Modules.GHIElectronics.MulticolorLed multicolorLed;
        Gadgeteer.Modules.GHIElectronics.Potentiometer potentiometer;
        Gadgeteer.Modules.Seeed.TemperatureHumidity temperatureHumidity;

        public static void Main()
        {
            //Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();			

            Program program = new Program();
            program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
            // Initialize GTM.Modules and event handlers here.		
            temperatureHumidity = new GTM.Seeed.TemperatureHumidity(6);
		
            ethernet_J11D = new GTM.GHIElectronics.Ethernet_J11D(7);
		
            multicolorLed = new GTM.GHIElectronics.MulticolorLed(8);
		
            potentiometer = new GTM.GHIElectronics.Potentiometer(9);
		
            lightSensor = new GTM.GHIElectronics.LightSensor(10);
		
            button = new GTM.GHIElectronics.Button(11);
		
            display_TE35 = new GTM.GHIElectronics.Display_TE35(14, 13, 12, Socket.Unused);

        }
    }
}
