//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FEZBalanceBot {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The CerbotController module (no sockets).</summary>
        private Gadgeteer.Modules.GHIElectronics.CerbotController controller;
        
        /// <summary>The Accelerometer module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.Seeed.Accelerometer accelerometer;
        
        /// <summary>The Gyro module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.Seeed.Gyro gyro;
        
        /// <summary>The Button module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        /// <summary>The IRreceiver module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.IR_Receiver irReceiver;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZCerbot Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZCerbot)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZCerbot();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.controller = new GTM.GHIElectronics.CerbotController();
            this.accelerometer = new GTM.Seeed.Accelerometer(5);
            this.gyro = new GTM.Seeed.Gyro(2);
            this.button = new GTM.GHIElectronics.Button(4);
            this.irReceiver = new GTM.GHIElectronics.IR_Receiver(3);
        }
    }
}
