//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace GadgeteerWcfRestService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class TDataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new TDataEntities object using the connection string found in the 'TDataEntities' section of the application configuration file.
        /// </summary>
        public TDataEntities() : base("name=TDataEntities", "TDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TDataEntities object.
        /// </summary>
        public TDataEntities(string connectionString) : base(connectionString, "TDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new TDataEntities object.
        /// </summary>
        public TDataEntities(EntityConnection connection) : base(connection, "TDataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TDataItem> TDataItems
        {
            get
            {
                if ((_TDataItems == null))
                {
                    _TDataItems = base.CreateObjectSet<TDataItem>("TDataItems");
                }
                return _TDataItems;
            }
        }
        private ObjectSet<TDataItem> _TDataItems;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TDataItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTDataItems(TDataItem tDataItem)
        {
            base.AddObject("TDataItems", tDataItem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TDataModel", Name="TDataItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TDataItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TDataItem object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="lightSENS">Initial value of the lightSENS property.</param>
        /// <param name="humSENS">Initial value of the humSENS property.</param>
        /// <param name="tempSENS">Initial value of the tempSENS property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static TDataItem CreateTDataItem(global::System.Int32 id, global::System.Int32 lightSENS, global::System.Int32 humSENS, global::System.Decimal tempSENS, global::System.DateTime date)
        {
            TDataItem tDataItem = new TDataItem();
            tDataItem.ID = id;
            tDataItem.lightSENS = lightSENS;
            tDataItem.humSENS = humSENS;
            tDataItem.tempSENS = tempSENS;
            tDataItem.Date = date;
            return tDataItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 lightSENS
        {
            get
            {
                return _lightSENS;
            }
            set
            {
                OnlightSENSChanging(value);
                ReportPropertyChanging("lightSENS");
                _lightSENS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lightSENS");
                OnlightSENSChanged();
            }
        }
        private global::System.Int32 _lightSENS;
        partial void OnlightSENSChanging(global::System.Int32 value);
        partial void OnlightSENSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 humSENS
        {
            get
            {
                return _humSENS;
            }
            set
            {
                OnhumSENSChanging(value);
                ReportPropertyChanging("humSENS");
                _humSENS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("humSENS");
                OnhumSENSChanged();
            }
        }
        private global::System.Int32 _humSENS;
        partial void OnhumSENSChanging(global::System.Int32 value);
        partial void OnhumSENSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal tempSENS
        {
            get
            {
                return _tempSENS;
            }
            set
            {
                OntempSENSChanging(value);
                ReportPropertyChanging("tempSENS");
                _tempSENS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tempSENS");
                OntempSENSChanged();
            }
        }
        private global::System.Decimal _tempSENS;
        partial void OntempSENSChanging(global::System.Decimal value);
        partial void OntempSENSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Transacto
        {
            get
            {
                return StructuralObject.GetValidValue(_Transacto);
            }
            set
            {
                OnTransactoChanging(value);
                ReportPropertyChanging("Transacto");
                _Transacto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Transacto");
                OnTransactoChanged();
            }
        }
        private global::System.Byte[] _Transacto;
        partial void OnTransactoChanging(global::System.Byte[] value);
        partial void OnTransactoChanged();

        #endregion
    
    }

    #endregion
    
}
