//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _GADGETEER2XIVELY_H_
#define _GADGETEER2XIVELY_H_

#include <TinyCLR_Interop.h>
struct Library_Gadgeteer2Xively_Gadgeteer2Xively_Resources
{
    static const int FIELD_STATIC__manager = 0;


    //--//

};

struct Library_Gadgeteer2Xively_Gadgeteer2Xively_Program
{
    static const int FIELD_STATIC__tempMeas = 1;
    static const int FIELD_STATIC__humMeas = 2;
    static const int FIELD_STATIC__lightMeas = 3;
    static const int FIELD_STATIC__compassAngleMeas = 4;
    static const int FIELD_STATIC__barometerMeas = 5;
    static const int FIELD_STATIC__potentiometerMeas = 6;
    static const int FIELD_STATIC__countDown = 7;
    static const int FIELD_STATIC__timer = 8;

    static const int FIELD__button = 4;
    static const int FIELD__display_TE35 = 5;
    static const int FIELD__ethernet_J11D = 6;
    static const int FIELD__lightSensor = 7;
    static const int FIELD__multicolorLed = 8;
    static const int FIELD__potentiometer = 9;
    static const int FIELD__temperatureHumidity = 10;
    static const int FIELD__barometer = 11;
    static const int FIELD__compass = 12;
    static const int FIELD__xyvStatus = 13;


    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Gadgeteer2Xively;

#endif  //_GADGETEER2XIVELY_H_
